services:

  mongodb:
    image: mongo:7.0
    container_name: smartcart-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: smartcart
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: smartcart-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: smartcart-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: smartcart-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./scripts/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zipkin:
    image: openzipkin/zipkin:3
    container_name: smartcart-zipkin
    ports:
      - "9411:9411"

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data: