spring:
  data:
    redis:
      host: localhost
      password: ""

    mongodb:
      uri: mongodb://localhost:27017/smartcart_local

  rabbitmq:
    host: localhost

logging:
  level:
    com.msd.smartcart: DEBUG